travis:
  secure:
    BINSTAR_TOKEN: ZGiooEk9rNU2uUIqGSnx8oXNQ/glseQQJjVeOh55gJxlNdUrI72rDIYbuAbuuKZOHC8I/nG/t+QfAxjcFFcwdKWuL8x+GnsaRN9G0kzjAqdKK0FLoseau3xjOGy8iTWjiDAjzgMOYcJEimXimefVKSVYqRZbse+uC0PCo9PtII9Gwoh5eov5q7MAGfZRJSTxTNFJz09kHcbGjA7tZwpubYsOgxSC2NVvSLK0133nXUqo3aC/c/+OM6+mukY9JLVk21mngO1nRlOsE1+DVRVLjRag9UH6j7poYH94cvV+kbvXOewFteIas+cfN5Z7PyZ+9eIFk52BOQyI/Ghzz8fabVzyKFDsYaJJbA5N4o+q/v8XLXBBVA7hoQRAtWVypTCV6sFb2kOVDXajgdeMfwNW4furdXuY0tZQ/RSs8zDxK1efPqQaEDdjxHfmSqorRAD7f6yChMLLyX3e4t8I7NpFnwUsgG6lKB5rR5BEI9Y+mReTpHuQrW1mkuGakLW97A7b5DLS8an0W5dbisyRbFnzq5+U9AM+2UXRZMCO2y6bUVXCUxzJ+Yo7tknljGSWIRJu3IhMknZy+CbmKB1OLYLbwrf+Iq78lxMWFAGjXKVlL9C/C0nliGmXirZra7zFrFH5kYMx6Vq+NpGvSM5TX+QMbiafjKYF8C/X3aQM4hxbE7k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
